### 添加请求
POST http://localhost:8181/sysActor
Content-Type: application/json

{
  "actorName": "肖战",
  "actorGender": true,
  "actorPhoto": "bablablablabla",
  "actorAge": 20,
  "actorHeight": 170.5,
  "actorSchool": "中央美院",
  "actorNation": "汉族",
  "actorBloodType": "B型",
  "actorConstellation": "水瓶座",
  "actorNationality": "中国",
  "actorInformation": "守护全世界最好的肖战割割"
}




### 查询所有
GET http://localhost:8181/sysActor?actorGender=true
Accept: application/json

### 查询一个
GET http://localhost:8181/sysActor/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysActor
Content-Type: application/json

{
  "actorId": 1,
  "actorName": "王一博",
  "actorPhoto": "https://www.4399.com",
  "actorHeight": 180.5,
  "actorGender": false,
  "actorSchool": "北京大学",
  "actorNation": "汉族",
  "actorBloodType": "A型",
  "actorConstellation": "水瓶座",
  "actorNationality": "中国",
  "actorInformation": "守护全世界最好的肖战割割"
}

### 删除
DELETE http://localhost:8181/sysActor/5


### 查询完整信息
GET http://localhost:8181/sysActor/find/1

