### 添加请求
POST http://localhost:8181/sysActorMovie
Content-Type: application/json

{
  "movieId": 3,
  "actorId": 5,
  "actorRoleId": 8
}


### 查询所有
GET http://localhost:8181/sysActorMovie
Accept: application/json


### 删除
POST http://localhost:8181/sysActorMovie/delete?movieId=1&actorId=2&actorRoleId=2
Content-Type: application/json

[
  {
    "movieId": 1,
    "actorId": 2,
    "actorRoleId": 2
  }
]

