### 添加请求
POST http://localhost:8181/sysActorRole
Content-Type: application/json

{"actorRoleName":"test0"}

### 查询所有
GET http://localhost:8181/sysActorRole?orderByColumn=actorRoleName&isAsc=desc
Accept: application/json

### 查询一个
GET http://localhost:8181/sysActorRole/3
Accept: application/json

### 修改
PUT http://localhost:8181/sysActorRole
Content-Type: application/json

{"actorRoleId":3,"actorRoleName":"修改0测试"}

### 删除
DELETE http://localhost:8181/sysActorRole/5
