### 添加请求
POST http://localhost:8181/sysCinema
Content-Type: application/json

{
  "cinemaName": "万达影城(大学店)",
  "cinemaBrand": "万达影城",
  "cinemaPicture": "[\"https://leetcode-cn.com/problems/design-linked-list/\"]",
  "isTicketChanged": true,
  "isRefunded": false,
  "cinemaAreaId": 1,
  "cinemaAddress": "金州区湾里街道金凯隆商城",
  "userId": 1,
  "entryDate": "2020-02-02"
}




### 查询所有
GET http://localhost:8181/sysCinema?cinemaBrandId=2
Accept: application/json

### 查询一个
GET http://localhost:8181/sysCinema/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysCinema
Content-Type: application/json

{
  "cinemaId": 3,
  "cinemaName": "哈哈哈影城",
  "cinemaBrand": "万达影城",
  "cinemaPicture": "[\"https://leetcode-cn.com/problems/design-linked-list/\"]",
  "isTicketChanged": true,
  "isRefunded": false,
  "cinemaAreaId": 1,
  "cinemaAddress": "甘井子区泉水瑞沃广场3楼",
  "userId": 2,
  "entryDate": "2020-02-02"
}

### 删除
DELETE http://localhost:8181/sysCinema/4

### 前台查询影院的详细信息
GET http://localhost:8181/sysCinema/find/1/1