### 查询所有
GET http://localhost:8181/sysHallCategory?pageNum=2&pageSize=5
Accept: application/json

### 查询一个
GET http://localhost:8181/sysHallCategory/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysHallCategory
Content-Type: application/json

{"hallCategoryId":2,"hallCategoryName":"修改测试"}

### 删除
DELETE http://localhost:8181/sysHallCategory/6

### 添加请求
POST http://localhost:8181/sysHallCategory
Content-Type: application/json

{"hallCategoryName":"普通影厅"}