### 添加请求
POST http://localhost:8181/sysMovieAge
Content-Type: application/json

{"movieAgeName":"test0"}


### 查询所有
GET http://localhost:8181/sysMovieAge?pageNum=1&pageSize=15&orderByColumn=movieAgeName
Accept: application/json

### 查询一个
GET http://localhost:8181/sysMovieAge/34
Accept: application/json

### 修改
PUT http://localhost:8181/sysMovieAge
Content-Type: application/json

{"movieAgeId":34,"movieAgeName":"修改0测试"}

### 删除
DELETE http://localhost:8181/sysMovieAge/34
