### 添加请求
POST http://localhost:8181/sysMovieComment
Content-Type: application/json

{
  "movieId": 4,
  "userId": 4,
  "commentTime": "2020-11-23 00:00:00",
  "content": "这部电影真的很很一般",
  "score": 9
}

### 查询所有
GET http://localhost:8181/sysMovieComment
Accept: application/json

### 查询指定电影评论
GET http://localhost:8181/sysMovieComment/4
Accept: application/json

### 查询指定用户评论
GET http://localhost:8181/sysUserComment/1
Accept: application/json

### 修改
PUT http://localhost:8181/sysMovieComment
Content-Type: application/json

{
  "movieId": 4,
  "userId": 1,
  "commentTime": "2020-11-24 10:49:54",
  "content": "这部电影真的烂透了",
  "score": 2.0
}

### 删除
POST http://localhost:8181/sysMovieComment/delete
Content-Type: application/json

[
  {
    "movieId": 4,
    "userId": 4,
    "commentTime": "2020-11-23 00:00:00",
    "score": 9
  }
]
