### 查询所有
GET http://localhost:8181/sysMovieCategory?pageNum=1&pageSize=5
Accept: application/json

### 查询一个
GET http://localhost:8181/sysMovieCategory/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysMovieCategory
Content-Type: application/json

{"movieCategoryId":2,"movieCategoryName":"修改测试"}

### 删除
DELETE http://localhost:8181/sysMovieCategory/5,6

### 添加请求
POST http://localhost:8181/sysMovieCategory
Content-Type: application/json

{"movieCategoryName":"历史"}