### 查询所有
GET http://localhost:8181/sysMovieArea?pageNum=2&pageSize=5
Accept: application/json

### 查询一个
GET http://localhost:8181/sysMovieArea/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysMovieArea
Content-Type: application/json

{"movieAreaId":2,"movieAreaName":"修改测试"}

### 删除
DELETE http://localhost:8181/sysMovieArea/3

### 添加请求
POST http://localhost:8181/sysMovieArea
Content-Type: application/json

{"movieAreaName":"美国"}