### 添加请求
POST http://localhost:8181/sysMovieToCategory
Content-Type: application/json

{
  "movieId": 1,
  "movieCategoryId": 3
}


### 查询所有
GET http://localhost:8181/sysMovieToCategory?movieId=1&movieCategoryId=1
Accept: application/json


### 删除
POST http://localhost:8181/sysMovieToCategory/delete
Content-Type: application/json

[
  {
    "movieId": 2,
    "movieCategoryId": 1
  },
  {
    "movieId": 1,
    "movieCategoryId": 3
  }
]

