### 添加请求
POST http://localhost:8181/sysMovieRuntime
Content-Type: application/json

{"movieRuntimeName":"test0", "beginTime": "12:00", "endTime": "13:30"}

### 查询所有
GET http://localhost:8181/sysMovieRuntime?pageSize=20&orderByColumn=movieRuntimeName&isAsc=desc
Accept: application/json

### 查询一个
GET http://localhost:8181/sysMovieRuntime/3
Accept: application/json

### 修改
PUT http://localhost:8181/sysMovieRuntime
Content-Type: application/json

{
  "movieRuntimeId": 3,
  "movieRuntimeName": "修改0测试",
  "beginTime": "10:00",
  "endTime": "11:30"
}

### 删除
DELETE http://localhost:8181/sysMovieRuntime/6,7
