### 添加请求
POST http://localhost:8181/sysMovie
Content-Type: application/json

{
  "movieNameCn": "一万",
  "movieNameEn": "Caught By Time",
  "movieLength": 120,
  "movieAreaId": 2
}

### 查询所有
GET http://localhost:8181/sysMovie
Accept: application/json

### 查询一个
GET http://localhost:8181/sysMovie/2
Accept: application/json

### 修改
PUT http://localhost:8181/sysMovie
Content-Type: application/json

{
  "movieId": 4,
  "movieNameCn": "除暴",
  "movieNameEn": "Caught By Time",
  "movieLength": 120
}

### 删除
DELETE http://localhost:8181/sysMovie/5,1,2,3

### 前台查询完整数据
GET http://localhost:8181/sysMovie/find/1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDgxMDMyMTMsInVzZXJuYW1lIjoiYWRtaW4ifQ.Em6B0pgTBBVUwxa6S4vsd_chvKOfDprMGK_BoZnC89I

### 查询榜单
GET http://localhost:8181/sysMovie/rankingList/4
