### 查询所有
GET http://localhost:8181/sysRole
Accept: application/json

### 查询一个
GET http://localhost:8181/sysRole/4
Accept: application/json

### 修改
PUT http://localhost:8181/sysRole
Content-Type: application/json

{
  "roleId": 4,
  "roleName": "修改测试",
  "roleDesc": "测试一下"
}

### 删除
DELETE http://localhost:8181/sysRole/4

### 添加请求
POST http://localhost:8181/sysRole
Content-Type: application/json

{
  "roleName": "普通影厅",
  "roleDesc": "测试一下"
}

### 给角色分配权限
POST http://localhost:8181/sysRole/1
Content-Type: application/json

[111, 121, 131]