
### 添加请求
POST http://localhost:8181/sysUser
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456",
  "email": "17777744455@qq.com",
  "phone": "13554785654",
  "sex": true,
  "userPicture": "http://qjx6d8hoy.hb-bkt.clouddn.com/images/IMG_0333.JPG"
}

### 查询所有
GET http://localhost:8181/sysUser
Accept: application/json

### 查询一个
GET http://localhost:8181/sysUser/3
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDc0OTk4OTUsInVzZXJuYW1lIjoi5ZGo5YWrIn0.RbEZ7YeX53SjrIiSzW0W5W23-vMP_kyCidiB4MVOC3U

### 修改
PUT http://localhost:8181/sysUser
Content-Type: application/json

{
  "userId": 4,
  "userName": "李四七",
  "password": "aaa",
  "userPicture": "[]",
  "information": "{\"birthday\":\"1999-2-10\", \"state\":\"很开心\", \"hobbies\": [1,2,3], \"signature\":\"夹断哥花式擦屁股\"}"
}

### 删除
DELETE http://localhost:8181/sysUser/5

### 登录用户
POST http://localhost:8181/sysUser/login
Content-Type: application/json

{
  "userName": "admin",
  "password": 123456
}

### 测试路径
GET http://localhost:8181/upload/delete?filePath=/images/user/2020/12/05/eac4c11d811d4c29aa7e8e3289a051fd.jpg